import type { CashDayCloseView, CashTotals, CashZReport } from "@/lib/cash/types";
const round = (n: number) => Math.round((n + Number.EPSILON) * 100) / 100;
const n = (value: unknown) => { const parsed = typeof value === "number" ? value : Number(value); return Number.isFinite(parsed) ? round(parsed) : 0; };
export const EMPTY_CASH_TOTALS: CashTotals = { grossSales:0,netSales:0,cashSales:0,cardSales:0,voucherSales:0,otherSales:0,refunds:0,cashRefunds:0,tips:0,discounts:0,taxesRecorded:0,cashIn:0,cashOut:0,expectedCash:0,paymentCount:0,refundCount:0,orderCount:0,voidedLineCount:0,voidedLineAmount:0,compedLineCount:0,compedLineAmount:0 };
export function normalizeCashTotals(input: Partial<CashTotals> | null | undefined): CashTotals {
  const grossSales=n(input?.grossSales), refunds=n(input?.refunds); const count=(v:unknown)=>Math.max(0,Math.trunc(n(v)));
  return {grossSales,netSales:input?.netSales==null?round(grossSales-refunds):n(input.netSales),cashSales:n(input?.cashSales),cardSales:n(input?.cardSales),voucherSales:n(input?.voucherSales),otherSales:n(input?.otherSales),refunds,cashRefunds:n(input?.cashRefunds),tips:n(input?.tips),discounts:n(input?.discounts),taxesRecorded:n(input?.taxesRecorded),cashIn:n(input?.cashIn),cashOut:n(input?.cashOut),expectedCash:n(input?.expectedCash),paymentCount:count(input?.paymentCount),refundCount:count(input?.refundCount),orderCount:count(input?.orderCount),voidedLineCount:count(input?.voidedLineCount),voidedLineAmount:n(input?.voidedLineAmount),compedLineCount:count(input?.compedLineCount),compedLineAmount:n(input?.compedLineAmount)};
}
export function sumCashTotals(items: Array<Partial<CashTotals>|null|undefined>): CashTotals {
  const all=items.map(normalizeCashTotals);
  const sum=(key:keyof CashTotals)=>round(all.reduce((total,item)=>total+item[key],0));
  return normalizeCashTotals({grossSales:sum("grossSales"),netSales:sum("netSales"),cashSales:sum("cashSales"),cardSales:sum("cardSales"),voucherSales:sum("voucherSales"),otherSales:sum("otherSales"),refunds:sum("refunds"),cashRefunds:sum("cashRefunds"),tips:sum("tips"),discounts:sum("discounts"),taxesRecorded:sum("taxesRecorded"),cashIn:sum("cashIn"),cashOut:sum("cashOut"),expectedCash:sum("expectedCash"),paymentCount:sum("paymentCount"),refundCount:sum("refundCount"),orderCount:sum("orderCount"),voidedLineCount:sum("voidedLineCount"),voidedLineAmount:sum("voidedLineAmount"),compedLineCount:sum("compedLineCount"),compedLineAmount:sum("compedLineAmount")});
}
export function cashSessionReportRows(report: CashZReport): Array<[string,string|number]> { const t=normalizeCashTotals(report.totals); return [["report_type","session_z"],["session_id",report.sessionId],["register",report.registerName],["operator",report.operatorEmail],["opened_at_ms",report.openedAtMs],["closed_at_ms",report.closedAtMs],["opening_float",report.openingFloat],["gross_sales",t.grossSales],["net_sales",t.netSales],["cash_sales",t.cashSales],["card_sales",t.cardSales],["voucher_sales",t.voucherSales],["other_sales",t.otherSales],["refunds",t.refunds],["tips",t.tips],["discounts",t.discounts],["taxes_recorded",t.taxesRecorded],["cash_in",t.cashIn],["cash_out",t.cashOut],["expected_cash",t.expectedCash],["counted_cash",report.countedCash],["difference",report.difference],["payment_count",t.paymentCount],["refund_count",t.refundCount],["order_count",t.orderCount],["voided_line_count",t.voidedLineCount],["voided_line_amount",t.voidedLineAmount],["comped_line_count",t.compedLineCount],["comped_line_amount",t.compedLineAmount],["discrepancy_reason",report.discrepancyReason??""]]; }
export function cashDayReportRows(day: CashDayCloseView): Array<[string,string|number]> { const t=normalizeCashTotals(day.totals); return [["report_type","day_z"],["business_date",day.businessDate],["timezone",day.timezone],["session_count",day.sessionCount],["session_ids",day.sessionIds.join("|")],["operators",day.operatorEmails.join("|")],["gross_sales",t.grossSales],["net_sales",t.netSales],["cash_sales",t.cashSales],["card_sales",t.cardSales],["voucher_sales",t.voucherSales],["other_sales",t.otherSales],["refunds",t.refunds],["tips",t.tips],["discounts",t.discounts],["taxes_recorded",t.taxesRecorded],["cash_in",t.cashIn],["cash_out",t.cashOut],["expected_cash",t.expectedCash],["total_opening_float",day.totalOpeningFloat],["total_counted_cash",day.totalCountedCash],["total_difference",day.totalDifference],["discrepancy_session_count",day.discrepancySessionCount],["payment_count",t.paymentCount],["refund_count",t.refundCount],["order_count",t.orderCount],["voided_line_count",t.voidedLineCount],["voided_line_amount",t.voidedLineAmount],["comped_line_count",t.compedLineCount],["comped_line_amount",t.compedLineAmount],["note",day.note??""]]; }
export function rowsToCsv(rows:Array<[string,string|number]>):string { const q=(v:string|number)=>`"${String(v??"").replaceAll('"','""')}"`; return ["field,value",...rows.map(([a,b])=>`${q(a)},${q(b)}`)].join("\n"); }
