"use client";

import { useCallback, useEffect, useState } from "react";
import { HostlyAlert, HostlyButton, HostlyCard, HostlyTextarea } from "@/components/ui/hostly";
import { cashDayReportRows, cashSessionReportRows, normalizeCashTotals } from "@/lib/cash/report";
import { downloadCashCsv, requestCashWorkspace, requestCloseCashDay } from "@/lib/cash/request-cash";
import type { CashDayCloseView, CashSessionView, CashTotals, CashWorkspaceSnapshot } from "@/lib/cash/types";

const eur=(value:number|null|undefined)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(value??0);
const dateTime=(value:number|null|undefined)=>value?new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";
function errorText(error:unknown){const code=error instanceof Error?error.message:"CASH_OPERATION_FAILED";const labels:Record<string,string>={CASH_DAY_ACTIVE_SESSION:"Cierra el turno antes de cerrar la jornada.",CASH_DAY_NO_SESSIONS:"No hay turnos cerrados de hoy para consolidar.",CASH_DAY_ALREADY_CLOSED:"La jornada ya está cerrada y sellada.",CASH_Z_REPORT_UNAVAILABLE:"Este cierre antiguo no dispone de informe Z sellado.",CASH_REPORT_INTEGRITY_MISMATCH:"El informe no supera la comprobación de integridad.",CASH_EXPORT_FAILED:"No se ha podido exportar el informe."};return labels[code]??"No se ha podido completar la operación.";}
function Integrity({status}:{status:"verified"|"missing"|"mismatch"|null|undefined}){const cls=status==="verified"?"bg-emerald-50 text-emerald-700":status==="mismatch"?"bg-rose-50 text-rose-700":"bg-slate-100 text-slate-600";return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${cls}`}>{status==="verified"?"Integridad verificada":status==="mismatch"?"Integridad alterada":"Cierre legacy"}</span>;}
function Metrics({totals}:{totals:CashTotals}){const safe=normalizeCashTotals(totals);const values:[[string,number],...[string,number][]]=[["Ventas netas",safe.netSales],["Efectivo",safe.cashSales],["Tarjeta",safe.cardSales],["Devoluciones",-safe.refunds],["Descuentos",safe.discounts],["Propinas",safe.tips],["Efectivo esperado",safe.expectedCash],["Anulaciones",safe.voidedLineAmount],["Invitaciones",safe.compedLineAmount]];return <div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-5">{values.map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 font-semibold text-slate-950">{eur(value)}</p></div>)}</div>;}
function printRows(title:string,rows:Array<[string,string|number]>){const win=window.open("","_blank","noopener,noreferrer,width=760,height=900");if(!win)return;const esc=(v:unknown)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:system-ui;margin:32px}table{width:100%;border-collapse:collapse}td{border-bottom:1px solid #ddd;padding:8px}</style></head><body><h1>${esc(title)}</h1><table>${rows.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join("")}</table><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close();}
function SessionZ({session,onExport}:{session:CashSessionView;onExport:(kind:"session"|"day",id:string)=>void}){if(!session.zReport)return <HostlyAlert tone="info">Cierre histórico anterior al informe Z sellado. Hostly no lo recrea retroactivamente.</HostlyAlert>;return <div className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold text-slate-950">Informe Z · {session.registerName}</p><p className="text-xs text-slate-500">{dateTime(session.openedAtMs)} → {dateTime(session.closedAtMs)}</p></div><Integrity status={session.integrityStatus}/></div><Metrics totals={session.zReport.totals}/><p className="text-sm text-slate-700">Contado {eur(session.zReport.countedCash)} · diferencia {eur(session.zReport.difference)} · {session.zReport.totals.paymentCount} cobro(s) · {session.zReport.totals.refundCount} devolución(es)</p><div className="flex gap-2"><HostlyButton variant="secondary" size="compact" disabled={session.integrityStatus==="mismatch"} onClick={()=>onExport("session",session.id)}>Exportar CSV</HostlyButton><HostlyButton variant="secondary" size="compact" onClick={()=>printRows(`Hostly · Informe Z ${session.id}`,cashSessionReportRows(session.zReport!))}>Imprimir</HostlyButton></div></div>;}
function DayClose({day,onExport}:{day:CashDayCloseView;onExport:(kind:"session"|"day",id:string)=>void}){return <div className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold text-slate-950">Cierre diario · {day.businessDate}</p><p className="text-xs text-slate-500">{day.sessionCount} turno(s) · {day.timezone}</p></div><Integrity status={day.integrityStatus}/></div><Metrics totals={day.totals}/><p className="text-sm text-slate-700">Fondos {eur(day.totalOpeningFloat)} · contado {eur(day.totalCountedCash)} · diferencia {eur(day.totalDifference)} · {day.discrepancySessionCount} turno(s) con descuadre</p><div className="flex gap-2"><HostlyButton variant="secondary" size="compact" disabled={day.integrityStatus==="mismatch"} onClick={()=>onExport("day",day.id)}>Exportar CSV</HostlyButton><HostlyButton variant="secondary" size="compact" onClick={()=>printRows(`Hostly · Cierre diario ${day.businessDate}`,cashDayReportRows(day))}>Imprimir</HostlyButton></div></div>;}

export function CashCloseOperationsPanel(){
  const [snapshot,setSnapshot]=useState<CashWorkspaceSnapshot|null>(null),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[sessionId,setSessionId]=useState<string|null>(null),[dayId,setDayId]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setSnapshot(await requestCashWorkspace());}catch{/* La página principal ya muestra errores de acceso. */}},[]);
  useEffect(()=>{void load();const id=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(id);},[load]);
  async function closeDay(){setBusy(true);setError("");setMessage("");try{await requestCloseCashDay(note);setMessage("Jornada cerrada y sellada correctamente.");setNote("");await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function exportCsv(kind:"session"|"day",id:string){setBusy(true);setError("");try{await downloadCashCsv(kind,id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  if(!snapshot)return null;
  const businessDate=snapshot.currentBusinessDate??"—",timezone=snapshot.timezone??"Europe/Madrid",dayClosures=snapshot.dayClosures??[],current=dayClosures.find(day=>day.businessDate===businessDate)??null;
  return <section className="mx-auto w-full max-w-[1240px] space-y-5 px-4 pb-8 md:px-6" aria-label="Cierres e informes de caja">
    {error?<HostlyAlert tone="danger">{error}</HostlyAlert>:null}{message?<HostlyAlert tone="success">{message}</HostlyAlert>:null}
    <HostlyCard className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-sky-700">Jornada {businessDate}</p><h2 className="text-lg font-semibold text-slate-950">Cierre diario e informes Z</h2><p className="text-sm text-slate-600">Zona horaria {timezone}. Los nuevos cierres quedan sellados con huella de integridad.</p></div>{current?<Integrity status={current.integrityStatus}/>:<span className="rounded-full bg-sky-50 px-2.5 py-1 text-xs font-semibold text-sky-700">Jornada abierta</span>}</div>{snapshot.canSupervise&&!current?<div className="space-y-3"><HostlyTextarea placeholder="Nota opcional del cierre diario" value={note} onChange={e=>setNote(e.target.value)}/><HostlyButton variant="primary" disabled={busy||!snapshot.canCloseDay} onClick={()=>void closeDay()}>Cerrar jornada</HostlyButton>{!snapshot.canCloseDay?<p className="text-xs text-slate-500">Para cerrar la jornada no puede haber una caja activa y debe existir al menos un turno cerrado hoy.</p>:null}</div>:null}</HostlyCard>
    {snapshot.history.length?<HostlyCard className="space-y-3 p-5"><h2 className="text-lg font-semibold text-slate-950">Informes Z por turno</h2>{snapshot.history.map(session=><div key={session.id} className="rounded-xl border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium text-slate-900">{dateTime(session.closedAtMs)} · {session.operatorEmail||"Operador"}</p><p className="text-xs text-slate-500">Ventas netas {eur(normalizeCashTotals(session.totals).netSales)} · diferencia {eur(session.difference)}</p></div><div className="flex items-center gap-2"><Integrity status={session.integrityStatus}/><HostlyButton variant="secondary" size="compact" onClick={()=>setSessionId(v=>v===session.id?null:session.id)}>{sessionId===session.id?"Ocultar":"Ver Z"}</HostlyButton></div></div>{sessionId===session.id?<div className="mt-3"><SessionZ session={session} onExport={(kind,id)=>void exportCsv(kind,id)}/></div>:null}</div>)}</HostlyCard>:null}
    {dayClosures.length?<HostlyCard className="space-y-3 p-5"><h2 className="text-lg font-semibold text-slate-950">Histórico de cierres diarios</h2>{dayClosures.map(day=><div key={day.id} className="rounded-xl border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium text-slate-900">{day.businessDate} · {eur(normalizeCashTotals(day.totals).netSales)} netos · diferencia {eur(day.totalDifference)}</p><HostlyButton variant="secondary" size="compact" onClick={()=>setDayId(v=>v===day.id?null:day.id)}>{dayId===day.id?"Ocultar":"Ver cierre"}</HostlyButton></div>{dayId===day.id?<div className="mt-3"><DayClose day={day} onExport={(kind,id)=>void exportCsv(kind,id)}/></div>:null}</div>)}</HostlyCard>:null}
  </section>;
}
