import assert from "node:assert/strict";
import test from "node:test";
import { businessDateForMs, resolveCashTimezone } from "@/lib/cash/business-day";
import { cashDayReportRows, cashSessionReportRows, normalizeCashTotals, rowsToCsv, sumCashTotals } from "@/lib/cash/report";
import type { CashDayCloseView, CashZReport } from "@/lib/cash/types";

test("legacy cash totals normalize safely",()=>{const t=normalizeCashTotals({grossSales:120,refunds:20,cashSales:60,cardSales:60,expectedCash:160});assert.equal(t.netSales,100);assert.equal(t.discounts,0);assert.equal(t.voidedLineCount,0);});
test("day totals aggregate operational metrics",()=>{const t=sumCashTotals([{grossSales:100,netSales:90,refunds:10,discounts:5,orderCount:4},{grossSales:80,netSales:80,discounts:2,orderCount:3,compedLineAmount:6}]);assert.equal(t.grossSales,180);assert.equal(t.netSales,170);assert.equal(t.discounts,7);assert.equal(t.orderCount,7);assert.equal(t.compedLineAmount,6);});
test("business day respects restaurant timezone",()=>{assert.equal(businessDateForMs(Date.UTC(2026,8,5,22,30),"Europe/Madrid"),"2026-09-06");assert.equal(resolveCashTimezone("invalid/timezone"),"Europe/Madrid");});
test("session Z CSV contains reconciliation controls",()=>{const z:CashZReport={version:1,reportType:"session_z",restaurantId:"r",sessionId:"s",registerId:"main",registerName:"Caja",operatorUid:"u",operatorEmail:"u@example.com",openedAtMs:1,closedAtMs:2,openingFloat:100,countedCash:150,difference:2,discrepancyReason:"ajuste",totals:normalizeCashTotals({grossSales:60,refunds:5,cashSales:50,cardSales:10,expectedCash:148,discounts:4,voidedLineCount:1}),generatedAtMs:2,generatedBy:"m"};const csv=rowsToCsv(cashSessionReportRows(z));assert.match(csv,/"expected_cash","148"/);assert.match(csv,/"difference","2"/);assert.match(csv,/"discounts","4"/);assert.match(csv,/"voided_line_count","1"/);});
test("daily CSV preserves exact shift references",()=>{const day:CashDayCloseView={id:"2026-09-05",businessDate:"2026-09-05",timezone:"Europe/Madrid",openedAtMs:1,closedAtMs:10,sessionIds:["s1","s2"],sessionCount:2,operatorEmails:["a@example.com"],totals:normalizeCashTotals({grossSales:200,netSales:190,refunds:10}),totalOpeningFloat:200,totalCountedCash:300,totalDifference:-2,discrepancySessionCount:1,closedBy:"m",closedByEmail:"m@example.com",note:null,integrityStatus:"verified"};const csv=rowsToCsv(cashDayReportRows(day));assert.match(csv,/"session_ids","s1\|s2"/);assert.match(csv,/"total_difference","-2"/);});
