import type {
  VisualAssetDefinition,
  VisualAssetDraft,
  VisualAssetKey,
} from "@/lib/sala-editor/visual-assets/visual-asset-types";
import {
  DEFAULT_VISUAL_ASSET_AI_FLAGS,
  DEFAULT_VISUAL_ASSET_TRANSFORM,
} from "@/lib/sala-editor/visual-assets/visual-asset-types";

function withAiTags(
  semanticTags: readonly string[],
): VisualAssetDefinition["aiFlags"] {
  return {
    ...DEFAULT_VISUAL_ASSET_AI_FLAGS,
    suggestable: true,
    replaceable: true,
    semanticTags,
  };
}

export const VISUAL_ASSET_CATALOG: readonly VisualAssetDefinition[] = [
  {
    type: "material",
    category: "surface",
    assetKey: "surface.neutral.default",
    label: "Suelo neutro",
    description: "Referencia visual futura para fondos discretos y mapas base.",
    variants: ["light", "warm", "dark"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.78,
    defaultVisualZIndex: 0,
    defaultRenderMode: "fill",
    aiFlags: withAiTags(["suelo neutro", "base", "fondo"]),
  },
  {
    type: "texture",
    category: "surface",
    assetKey: "surface.stone.default",
    label: "Textura de piedra",
    description: "Referencia visual futura para superficies minerales.",
    variants: ["light", "dark", "irregular"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 0,
    defaultRenderMode: "tile",
    aiFlags: withAiTags(["piedra", "terraza", "mineral"]),
  },
  {
    type: "texture",
    category: "surface",
    assetKey: "surface.wood.default",
    label: "Textura de madera",
    description: "Referencia visual futura para tarimas y salones calidos.",
    variants: ["oak", "walnut", "deck"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 0,
    defaultRenderMode: "tile",
    aiFlags: withAiTags(["madera", "tarima", "interior"]),
  },
  {
    type: "texture",
    category: "surface",
    assetKey: "surface.grass.default",
    label: "Cesped",
    description: "Referencia visual futura para jardines y zonas exteriores.",
    variants: ["short", "dense", "soft"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 0,
    defaultRenderMode: "tile",
    aiFlags: withAiTags(["cesped", "jardin", "exterior"]),
  },
  {
    type: "texture",
    category: "surface",
    assetKey: "surface.sand.default",
    label: "Arena",
    description: "Referencia visual futura para beach clubs y zonas de playa.",
    variants: ["fine", "warm", "pale"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 0,
    defaultRenderMode: "tile",
    aiFlags: withAiTags(["arena", "playa", "exterior"]),
  },
  {
    type: "texture",
    category: "surface",
    assetKey: "surface.tile.default",
    label: "Baldosas",
    description: "Referencia visual futura para suelos de baldosa.",
    variants: ["small", "large", "patterned"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 0,
    defaultRenderMode: "pattern",
    aiFlags: withAiTags(["baldosa", "suelo", "interior"]),
  },
  {
    type: "material",
    category: "surface",
    assetKey: "surface.marble.default",
    label: "Marmol",
    description: "Referencia visual futura para pavimentos nobles y barras premium.",
    variants: ["white", "cream", "dark", "green"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.88,
    defaultVisualZIndex: 0,
    defaultRenderMode: "pattern",
    aiFlags: withAiTags(["marmol", "hotel", "premium"]),
  },
  {
    type: "material",
    category: "surface",
    assetKey: "surface.concrete.default",
    label: "Hormigon",
    description: "Referencia visual futura para suelos neutros o industriales.",
    variants: ["smooth", "rough", "polished"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 0,
    defaultRenderMode: "tile",
    aiFlags: withAiTags(["hormigon", "industrial", "neutro"]),
  },
  {
    type: "water",
    category: "water",
    assetKey: "water.pool.default",
    label: "Piscina",
    description: "Referencia visual futura para laminas de agua o piscinas.",
    variants: ["blue", "turquoise", "dark"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 1,
    defaultRenderMode: "cover",
    aiFlags: withAiTags(["piscina", "agua", "beach club"]),
  },
  {
    type: "water",
    category: "water",
    assetKey: "water.fountain.default",
    label: "Fuente",
    description: "Referencia visual futura para fuentes y agua contenida.",
    variants: ["round", "linear", "low"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.76,
    defaultVisualZIndex: 1,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["fuente", "patio", "agua"]),
  },
  {
    type: "water",
    category: "water",
    assetKey: "water.sheet.default",
    label: "Lamina de agua",
    description: "Referencia visual futura para laminas de agua decorativas y no transitables.",
    variants: ["patio", "garden", "premium"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.72,
    defaultVisualZIndex: 1,
    defaultRenderMode: "cover",
    aiFlags: withAiTags(["lamina de agua", "hotel", "patio"]),
  },
  {
    type: "vegetation",
    category: "vegetation",
    assetKey: "vegetation.tree.default",
    label: "Arbol",
    description: "Referencia visual futura para vegetacion general.",
    variants: ["small", "medium", "large"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["arbol", "sombra", "vegetacion"]),
  },
  {
    type: "vegetation",
    category: "vegetation",
    assetKey: "vegetation.palm.default",
    label: "Palmera",
    description: "Referencia visual futura para espacios tropicales o playa.",
    variants: ["short", "tall", "wide"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["palmera", "playa", "terraza"]),
  },
  {
    type: "vegetation",
    category: "vegetation",
    assetKey: "vegetation.olive.default",
    label: "Olivo",
    description: "Referencia visual futura para terrazas mediterraneas.",
    variants: ["small", "medium", "old"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["olivo", "mediterraneo", "vegetacion"]),
  },
  {
    type: "vegetation",
    category: "vegetation",
    assetKey: "vegetation.shrub.default",
    label: "Arbusto",
    description: "Referencia visual futura para masas vegetales bajas y bordes de jardin.",
    variants: ["low", "irregular", "border"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.7,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["arbusto", "seto", "jardin"]),
  },
  {
    type: "vegetation",
    category: "vegetation",
    assetKey: "vegetation.hedge.default",
    label: "Seto",
    description: "Referencia visual futura para limites vegetales continuos.",
    variants: ["low", "high", "curved"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.76,
    defaultVisualZIndex: 2,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["seto", "limite vegetal", "privacidad"]),
  },
  {
    type: "vegetation",
    category: "vegetation",
    assetKey: "vegetation.flowers.default",
    label: "Flores",
    description: "Referencia visual futura para acentos vegetales controlados.",
    variants: ["white", "lavender", "bougainvillea", "coral"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.68,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["flores", "acento", "hotel"]),
  },
  {
    type: "object",
    category: "decor",
    assetKey: "decor.planter.default",
    label: "Jardinera",
    description: "Referencia visual futura para separacion vegetal.",
    variants: ["rectangular", "round", "long"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["jardinera", "separador", "vegetal"]),
  },
  {
    type: "object",
    category: "decor",
    assetKey: "decor.rug.default",
    label: "Alfombra lounge",
    description: "Referencia visual futura para alfombras, tapices y zonas lounge.",
    variants: ["rectangular", "round", "runner"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.74,
    defaultVisualZIndex: 1,
    defaultRenderMode: "pattern",
    aiFlags: withAiTags(["alfombra", "lounge", "tapiz"]),
  },
  {
    type: "object",
    category: "decor",
    assetKey: "decor.screen.default",
    label: "Biombo",
    description: "Referencia visual futura para separacion decorativa ligera.",
    variants: ["straight", "folding", "curved"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["biombo", "separador", "decoracion"]),
  },
  {
    type: "object",
    category: "decor",
    assetKey: "decor.sculpture.default",
    label: "Escultura",
    description: "Referencia visual futura para hitos decorativos sobrios.",
    variants: ["abstract", "totem", "hotel"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["escultura", "hito", "hotel"]),
  },
  {
    type: "object",
    category: "decor",
    assetKey: "decor.fire-pit.default",
    label: "Brasero",
    description: "Referencia visual futura para fuego exterior premium.",
    variants: ["round", "linear", "lounge"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["brasero", "fuego", "exterior"]),
  },
  {
    type: "object",
    category: "shade",
    assetKey: "shade.umbrella.default",
    label: "Sombrilla",
    description: "Referencia visual futura para sombra exterior.",
    variants: ["central", "side", "beach"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.9,
    defaultVisualZIndex: 3,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["sombrilla", "sombra", "terraza"]),
  },
  {
    type: "object",
    category: "shade",
    assetKey: "shade.awning.default",
    label: "Toldo",
    description: "Referencia visual futura para toldos y velas de sombra.",
    variants: ["fixed", "sail", "textile"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.78,
    defaultVisualZIndex: 3,
    defaultRenderMode: "cover",
    aiFlags: withAiTags(["toldo", "sombra", "exterior"]),
  },
  {
    type: "object",
    category: "exterior",
    assetKey: "exterior.pergola.default",
    label: "Pergola",
    description: "Referencia visual futura para estructuras exteriores ligeras.",
    variants: ["open", "covered", "vegetal"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 3,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["pergola", "exterior", "estructura"]),
  },
  {
    type: "object",
    category: "exterior",
    assetKey: "exterior.cabana.default",
    label: "Cabana",
    description: "Referencia visual futura para lounge exterior premium.",
    variants: ["open", "closed", "vip"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 3,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["cabana", "lounge", "resort"]),
  },
  {
    type: "object",
    category: "exterior",
    assetKey: "exterior.path.default",
    label: "Camino exterior",
    description: "Referencia visual futura para circulacion exterior.",
    variants: ["straight", "organic", "stepping-stones"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.78,
    defaultVisualZIndex: 1,
    defaultRenderMode: "pattern",
    aiFlags: withAiTags(["camino", "circulacion", "exterior"]),
  },
  {
    type: "object",
    category: "exterior",
    assetKey: "exterior.low-fence.default",
    label: "Valla baja",
    description: "Referencia visual futura para limites exteriores ligeros.",
    variants: ["wood", "rope", "metal"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["valla", "limite", "terraza"]),
  },
  {
    type: "object",
    category: "exterior",
    assetKey: "exterior.shower.default",
    label: "Ducha exterior",
    description: "Referencia visual futura para piscinas y beach clubs.",
    variants: ["single", "double"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["ducha", "piscina", "playa"]),
  },
  {
    type: "object",
    category: "decor",
    assetKey: "decor.rock.default",
    label: "Roca",
    description: "Referencia visual futura para decoracion mineral.",
    variants: ["small", "large", "group"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["roca", "mineral", "decoracion"]),
  },
  {
    type: "object",
    category: "decor",
    assetKey: "decor.fountain.default",
    label: "Fuente",
    description: "Referencia visual futura para elementos de agua decorativos.",
    variants: ["round", "wall", "small"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 2,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["fuente", "agua", "decoracion"]),
  },
  {
    type: "object",
    category: "structure",
    assetKey: "structure.bar.default",
    label: "Barra",
    description: "Referencia visual futura para barras fijas o mostradores.",
    variants: ["straight", "corner", "island"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 3,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["barra", "mostrador", "servicio"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.sofa.default",
    label: "Sofa",
    description: "Referencia visual futura para asientos lounge.",
    variants: ["two-seat", "three-seat", "corner"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["sofa", "lounge", "asiento"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.table.round.default",
    label: "Mesa redonda",
    description: "Referencia visual futura para mesas redondas operativas.",
    variants: ["2p", "4p", "6p"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["mesa", "redonda", "operacion"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.table.rectangular.default",
    label: "Mesa rectangular",
    description: "Referencia visual futura para mesas rectangulares operativas.",
    variants: ["2p", "4p", "6p", "8p"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["mesa", "rectangular", "operacion"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.table.square.default",
    label: "Mesa cuadrada",
    description: "Referencia visual futura para mesas cuadradas modulares.",
    variants: ["single", "modular", "terrace"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["mesa", "cuadrada", "terraza"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.chair.default",
    label: "Silla",
    description: "Referencia visual futura para lectura de capacidad.",
    variants: ["side", "armchair", "outdoor"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["silla", "capacidad", "mesa"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.stool.default",
    label: "Taburete",
    description: "Referencia visual futura para barras y mesas altas.",
    variants: ["low", "high", "bar"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["taburete", "barra", "mesa alta"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.low-table.default",
    label: "Mesa baja",
    description: "Referencia visual futura para lounges y sofas.",
    variants: ["round", "oval", "rectangular"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["mesa baja", "lounge", "sofa"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.balinese-bed.default",
    label: "Cama balinesa",
    description: "Referencia visual futura para servicio premium de piscina/playa.",
    variants: ["single", "double", "canopy"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["cama balinesa", "vip", "piscina"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.sunbed.default",
    label: "Hamaca",
    description: "Referencia visual futura para piscina, playa y wellness.",
    variants: ["single", "double", "reclined"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["hamaca", "piscina", "playa"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.service-station.default",
    label: "Punto camarero",
    description: "Referencia visual futura para estaciones de servicio compactas.",
    variants: ["station", "cabinet", "console"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["punto camarero", "servicio", "estacion"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.reception.default",
    label: "Recepcion",
    description: "Referencia visual futura para host stand y recepcion.",
    variants: ["hotel", "restaurant", "event"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["recepcion", "host stand", "entrada"]),
  },
  {
    type: "furniture",
    category: "furniture",
    assetKey: "furniture.pickup-point.default",
    label: "Punto recogida",
    description: "Referencia visual futura para takeaway y delivery.",
    variants: ["delivery", "pickup", "quick-service"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 1,
    defaultVisualZIndex: 4,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["pickup", "delivery", "recogida"]),
  },
  {
    type: "lighting",
    category: "lighting",
    assetKey: "lighting.ambient.default",
    label: "Iluminacion",
    description: "Referencia visual futura para puntos o zonas de luz.",
    variants: ["warm", "neutral", "accent"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.85,
    defaultVisualZIndex: 5,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["iluminacion", "ambiente", "luz"]),
  },
  {
    type: "lighting",
    category: "lighting",
    assetKey: "lighting.string.default",
    label: "Guirnalda",
    description: "Referencia visual futura para terrazas y patios.",
    variants: ["straight", "zigzag", "patio"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.72,
    defaultVisualZIndex: 5,
    defaultRenderMode: "pattern",
    aiFlags: withAiTags(["guirnalda", "terraza", "luz"]),
  },
  {
    type: "lighting",
    category: "lighting",
    assetKey: "lighting.linear-bar.default",
    label: "Luz lineal barra",
    description: "Referencia visual futura para barras y hoteles.",
    variants: ["front", "back", "floor"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.72,
    defaultVisualZIndex: 5,
    defaultRenderMode: "contain",
    aiFlags: withAiTags(["luz lineal", "barra", "hotel"]),
  },
  {
    type: "lighting",
    category: "lighting",
    assetKey: "lighting.bollard.default",
    label: "Baliza exterior",
    description: "Referencia visual futura para caminos exteriores.",
    variants: ["garden", "pool", "resort"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.72,
    defaultVisualZIndex: 5,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["baliza", "camino", "exterior"]),
  },
  {
    type: "lighting",
    category: "lighting",
    assetKey: "lighting.pendant.default",
    label: "Lampara colgante",
    description: "Referencia visual futura para interiores y clusters de luz.",
    variants: ["single", "cluster"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.76,
    defaultVisualZIndex: 5,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["lampara", "interior", "luz"]),
  },
  {
    type: "lighting",
    category: "lighting",
    assetKey: "lighting.functional.default",
    label: "Foco funcional",
    description: "Referencia visual futura para zonas de servicio.",
    variants: ["kitchen", "pickup", "bar"],
    defaultScale: 1,
    defaultRotation: 0,
    defaultOpacity: 0.74,
    defaultVisualZIndex: 5,
    defaultRenderMode: "stamp",
    aiFlags: withAiTags(["foco", "servicio", "funcional"]),
  },
] as const;

export function getVisualAssetDefinition(
  assetKey: VisualAssetKey | null | undefined,
): VisualAssetDefinition | null {
  if (!assetKey) return null;
  return VISUAL_ASSET_CATALOG.find((asset) => asset.assetKey === assetKey) ?? null;
}

export function createVisualAssetDraftFromDefinition(
  definition: VisualAssetDefinition,
  overrides: Partial<
    Pick<
      VisualAssetDraft,
      | "variant"
      | "scale"
      | "rotation"
      | "opacity"
      | "visualZIndex"
      | "renderMode"
      | "aiFlags"
    >
  > = {},
): VisualAssetDraft {
  return {
    type: definition.type,
    category: definition.category,
    assetKey: definition.assetKey,
    ...(overrides.variant ? { variant: overrides.variant } : {}),
    scale: overrides.scale ?? definition.defaultScale,
    rotation: overrides.rotation ?? definition.defaultRotation,
    opacity: overrides.opacity ?? definition.defaultOpacity,
    visualZIndex: overrides.visualZIndex ?? definition.defaultVisualZIndex,
    renderMode: overrides.renderMode ?? definition.defaultRenderMode,
    aiFlags: overrides.aiFlags ?? definition.aiFlags,
  };
}

export function createVisualAssetDraftFromKey(
  assetKey: VisualAssetKey,
  overrides?: Parameters<typeof createVisualAssetDraftFromDefinition>[1],
): VisualAssetDraft | null {
  const definition = getVisualAssetDefinition(assetKey);
  if (!definition) return null;
  return createVisualAssetDraftFromDefinition(definition, overrides);
}

export const DEFAULT_VISUAL_ASSET_DRAFT: VisualAssetDraft = {
  type: "material",
  category: "surface",
  assetKey: "surface.neutral.default",
  scale: DEFAULT_VISUAL_ASSET_TRANSFORM.scale,
  rotation: DEFAULT_VISUAL_ASSET_TRANSFORM.rotation,
  opacity: DEFAULT_VISUAL_ASSET_TRANSFORM.opacity,
  visualZIndex: DEFAULT_VISUAL_ASSET_TRANSFORM.visualZIndex,
  renderMode: DEFAULT_VISUAL_ASSET_TRANSFORM.renderMode,
  aiFlags: DEFAULT_VISUAL_ASSET_AI_FLAGS,
};
