"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import ModulePageShell from "@/components/module-page-shell";
import { HostlyButton, HostlyInput, HostlyTextarea } from "@/components/ui/hostly";
import type { CustomerCrmRecord, CustomerCrmSnapshot } from "@/lib/customers/types";
import type { CustomerSegment, MarketingConsent } from "@/lib/customers/crm-v2-policy";
import { configureCustomerLoyalty, redeemCustomerReward, requestCustomerCrm, saveCustomerCrmProfile } from "@/lib/customers/request-customer-crm";

const SEGMENT_LABELS: Record<CustomerSegment, string> = { vip:"VIP", frequent:"Frecuentes", new:"Nuevos", inactive:"Inactivos 90d", birthday_30d:"Cumpleaños 30d", no_show:"No-show", high_spend:"Alto gasto", marketing_opt_in:"Marketing OK" };
function eur(value:number){return new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(value||0)}
function visitMoment(visit:CustomerCrmRecord["lastVisit"]){if(!visit)return"—";const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(visit.date);return `${m?`${m[3]}/${m[2]}/${m[1]}`:visit.date} · ${visit.time}`}
type Editor={profileId:string|null;sourceKeys:string[];displayName:string;phone:string;email:string;birthday:string;vip:boolean;tagsText:string;allergies:string;preferences:string;notes:string;marketingConsent:MarketingConsent};
function editorFromRecord(r:CustomerCrmRecord):Editor{return{profileId:r.profileId,sourceKeys:r.sourceKeys,displayName:r.displayName,phone:r.phone,email:r.email,birthday:r.birthday,vip:r.vip,tagsText:r.tags.join(", "),allergies:r.allergies,preferences:r.preferences,notes:r.notes,marketingConsent:r.marketingConsent??"unknown"}}

export default function CustomersPage(){
 const[snapshot,setSnapshot]=useState<CustomerCrmSnapshot|null>(null);const[selectedId,setSelectedId]=useState<string|null>(null);const[editor,setEditor]=useState<Editor|null>(null);const[query,setQuery]=useState("");const[segment,setSegment]=useState<CustomerSegment|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 const[loyaltyEnabled,setLoyaltyEnabled]=useState(false);const[visitGoal,setVisitGoal]=useState(10);const[rewardLabel,setRewardLabel]=useState("Detalle de la casa");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const next=await requestCustomerCrm();setSnapshot(next);setLoyaltyEnabled(next.loyalty?.enabled??false);setVisitGoal(next.loyalty?.visitGoal??10);setRewardLabel(next.loyalty?.rewardLabel??"Detalle de la casa");setSelectedId(c=>c&&next.records.some(r=>r.recordId===c)?c:next.records[0]?.recordId??null)}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar Clientes")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("es-ES");return(snapshot?.records??[]).filter(r=>{if(segment&&!r.segments?.includes(segment))return false;if(!needle)return true;return[r.displayName,r.phone,r.email,...r.tags].join(" ").toLocaleLowerCase("es-ES").includes(needle)})},[snapshot,query,segment]);
 const selected=snapshot?.records.find(r=>r.recordId===selectedId)??null;useEffect(()=>{setEditor(selected?editorFromRecord(selected):null)},[selected]);
 const save=async()=>{if(!editor||!snapshot?.canEdit)return;setSaving(true);setError("");try{await saveCustomerCrmProfile({profileId:editor.profileId,sourceKeys:editor.sourceKeys,displayName:editor.displayName,phone:editor.phone,email:editor.email,birthday:editor.birthday,vip:editor.vip,tags:editor.tagsText.split(",").map(x=>x.trim()).filter(Boolean),allergies:editor.allergies,preferences:editor.preferences,notes:editor.notes,marketingConsent:editor.marketingConsent});await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar")}finally{setSaving(false)}};
 const saveLoyalty=async()=>{setSaving(true);setError("");try{await configureCustomerLoyalty({enabled:loyaltyEnabled,visitGoal,rewardLabel});await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar fidelización")}finally{setSaving(false)}};
 const redeem=async()=>{if(!selected?.profileId)return;setSaving(true);setError("");try{await redeemCustomerReward(selected.profileId);await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo canjear")}finally{setSaving(false)}};
 const summary=snapshot?.summary;
 return <ModulePageShell title="Clientes" subtitle="CRM, fidelización y segmentos del restaurante" maxWidth={1440} compactLayout shellSurface="configLight"><div className="flex min-h-0 flex-1 flex-col gap-4 px-3 pb-4 sm:px-5">
  <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-3"><Link href="/dashboard/operacion/reservas" className="text-sm font-semibold text-sky-700 hover:underline">← Reservas</Link><Link href="/dashboard/operacion/tpv" className="text-sm font-semibold text-sky-700 hover:underline">Abrir TPV</Link></div><HostlyButton variant="secondary" size="compact" onClick={()=>void load()} disabled={loading}>Actualizar</HostlyButton></div>
  {error?<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
  <section className="grid grid-cols-2 gap-2 lg:grid-cols-6">{[["Clientes",summary?.totalCustomers??0],["VIP",summary?.vipCustomers??0],["Recurrentes",summary?.repeatCustomers??0],["Marketing OK",summary?.marketingOptIn??0],["Premios disponibles",summary?.rewardsAvailable??0],["Gasto",eur(summary?.totalAttributedSpend??0)]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{l}</div><div className="mt-1 text-xl font-bold text-slate-900">{v}</div></div>)}</section>
  {snapshot?.canManageLoyalty?<section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={loyaltyEnabled} onChange={e=>setLoyaltyEnabled(e.target.checked)}/> Fidelización activa</label><label className="text-xs font-semibold text-slate-600">Visitas por premio<HostlyInput type="number" min={2} max={50} value={visitGoal} onChange={e=>setVisitGoal(Number(e.target.value)||10)}/></label><label className="min-w-56 flex-1 text-xs font-semibold text-slate-600">Premio<HostlyInput value={rewardLabel} onChange={e=>setRewardLabel(e.target.value)} placeholder="Detalle de la casa"/></label><HostlyButton size="compact" onClick={()=>void saveLoyalty()} disabled={saving}>Guardar fidelización</HostlyButton></div><p className="mt-2 text-xs text-slate-500">Los premios se calculan por visitas completadas. El canje siempre requiere acción de un responsable.</p></section>:null}
  <section className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[minmax(320px,.9fr)_minmax(0,1.5fr)]">
   <div className="flex min-h-0 flex-col rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-3"><HostlyInput value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nombre, teléfono, email o etiqueta"/><div className="mt-2 flex flex-wrap gap-1.5"><HostlyButton variant={!segment?"primary":"secondary"} size="compact" onClick={()=>setSegment(null)}>Todos</HostlyButton>{(Object.keys(SEGMENT_LABELS) as CustomerSegment[]).map(k=><HostlyButton key={k} variant={segment===k?"primary":"secondary"} size="compact" onClick={()=>setSegment(k)}>{SEGMENT_LABELS[k]}</HostlyButton>)}</div></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-2">{loading?<p className="p-3 text-sm text-slate-500">Cargando…</p>:null}{!loading&&filtered.length===0?<p className="p-3 text-sm text-slate-500">Sin clientes para este filtro.</p>:null}{filtered.map(r=><button key={r.recordId} type="button" onClick={()=>setSelectedId(r.recordId)} className={`mb-2 w-full rounded-xl border p-3 text-left ${r.recordId===selectedId?"border-sky-300 bg-sky-50":"border-slate-200 hover:bg-slate-50"}`}><div className="flex justify-between gap-2"><span className="truncate font-semibold text-slate-900">{r.displayName}</span>{r.vip?<span className="rounded-full bg-amber-100 px-2 py-.5 text-xs font-bold text-amber-800">VIP</span>:null}</div><div className="mt-1 text-xs text-slate-500">{r.completedVisits} visitas · {eur(r.totalSpend)} · {r.tpvVisits??0} TPV</div><div className="mt-1 flex flex-wrap gap-1">{r.segments?.slice(0,3).map(s=><span key={s} className="rounded-full bg-slate-100 px-1.5 py-.5 text-[10px] text-slate-600">{SEGMENT_LABELS[s]}</span>)}</div></button>)}</div>
   </div>
   <div className="min-h-0 overflow-y-auto rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">{!selected||!editor?<p className="text-sm text-slate-500">Selecciona un cliente.</p>:<div className="space-y-5">
    <header className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-2xl font-bold text-slate-950">{selected.displayName}</h2>{selected.vip?<span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-800">VIP</span>:null}</div><p className="mt-1 text-sm text-slate-500">Última: {visitMoment(selected.lastVisit)} · Próxima: {visitMoment(selected.nextReservation)}</p></div><div className="text-right"><div className="text-2xl font-bold">{eur(selected.totalSpend)}</div><div className="text-xs text-slate-500">{eur(selected.averageSpend)} media</div></div></header>
    <div className="grid gap-2 sm:grid-cols-5">{[["Visitas",selected.completedVisits],["TPV",selected.tpvVisits??0],["Reservas",selected.reservations],["No-show",selected.noShows],["Premios",selected.loyaltyAvailableRewards??0]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{l}</div><div className="text-lg font-bold">{v}</div></div>)}</div>
    {(snapshot?.loyalty?.enabled&&selected.profileId)?<div className="rounded-xl border border-sky-100 bg-sky-50 p-3"><div className="text-sm font-semibold text-sky-950">Fidelización: {selected.loyaltyProgress??0}/{snapshot.loyalty.visitGoal} hacia “{snapshot.loyalty.rewardLabel}”</div>{(selected.loyaltyAvailableRewards??0)>0&&snapshot.canManageLoyalty?<HostlyButton className="mt-2" size="compact" onClick={()=>void redeem()} disabled={saving}>Canjear 1 premio</HostlyButton>:null}</div>:null}
    <section><h3 className="mb-2 font-bold">Ficha</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Nombre<HostlyInput value={editor.displayName} onChange={e=>setEditor({...editor,displayName:e.target.value})} disabled={!snapshot?.canEdit}/></label><label className="text-sm">Teléfono<HostlyInput value={editor.phone} onChange={e=>setEditor({...editor,phone:e.target.value})} disabled={!snapshot?.canEdit}/></label><label className="text-sm">Email<HostlyInput value={editor.email} onChange={e=>setEditor({...editor,email:e.target.value})} disabled={!snapshot?.canEdit}/></label><label className="text-sm">Cumpleaños<HostlyInput type="date" value={editor.birthday} onChange={e=>setEditor({...editor,birthday:e.target.value})} disabled={!snapshot?.canEdit}/></label></div>
     <label className="mt-3 block text-sm">Etiquetas<HostlyInput value={editor.tagsText} onChange={e=>setEditor({...editor,tagsText:e.target.value})} disabled={!snapshot?.canEdit}/></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">Alergias<HostlyTextarea value={editor.allergies} onChange={e=>setEditor({...editor,allergies:e.target.value})} disabled={!snapshot?.canEdit}/></label><label className="text-sm">Preferencias<HostlyTextarea value={editor.preferences} onChange={e=>setEditor({...editor,preferences:e.target.value})} disabled={!snapshot?.canEdit}/></label></div><label className="mt-3 block text-sm">Notas internas<HostlyTextarea value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})} disabled={!snapshot?.canEdit}/></label>
     <div className="mt-3 rounded-xl border border-slate-200 p-3"><label className="text-sm font-semibold">Consentimiento comercial<select className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3" value={editor.marketingConsent} onChange={e=>setEditor({...editor,marketingConsent:e.target.value as MarketingConsent})} disabled={!snapshot?.canEdit}><option value="unknown">No consta</option><option value="granted">Aceptado expresamente</option><option value="denied">Rechazado</option></select></label><p className="mt-1 text-xs text-slate-500">Solo registra lo que el cliente haya indicado. No envía mensajes automáticamente.</p></div>
     {snapshot?.canManageVip?<label className="mt-3 flex gap-2 text-sm font-semibold"><input type="checkbox" checked={editor.vip} onChange={e=>setEditor({...editor,vip:e.target.checked})}/> Cliente VIP</label>:null}{snapshot?.canEdit?<HostlyButton className="mt-4" onClick={()=>void save()} disabled={saving}>{saving?"Guardando…":"Guardar ficha"}</HostlyButton>:null}
    </section>
    <section><h3 className="mb-2 font-bold">Historial</h3><div className="space-y-2">{selected.timeline.length===0?<p className="text-sm text-slate-500">Todavía no hay visitas vinculadas.</p>:selected.timeline.map(v=><div key={v.id??v.reservationId} className="grid gap-1 rounded-xl border border-slate-200 p-3 sm:grid-cols-[150px_1fr_auto] sm:items-center"><div className="text-sm font-semibold">{visitMoment(v)}</div><div className="text-sm text-slate-600">{v.source==="tpv"?"TPV":"Reserva"} · {v.tableLabel||"Sin mesa"} · {v.partySize} pax · {v.status}</div><div className="text-sm font-bold">{v.spend>0?eur(v.spend):"—"}</div></div>)}</div></section>
   </div>}</div>
  </section>
 </div></ModulePageShell>
}
